Better error checking/handling

diff --git a/secretctl b/secretctl
--- a/secretctl
+++ b/secretctl
@@ -17,7 +17,9 @@ Generate a key with: gpg --gen-key
 
 Commands:
 
-  export KEYID [KEYNAME]  Adds a new key that will be used in future encryptions
+  export KEYID [KEYNAME]  Exports a gpg key to be shared for future encryptions.
+                              Exports to .gpg-keys keydir searching up from working dir
+                              Will create .gpg-keys in current directory if not found
                           KEYID is the hex ID of a public key which is output when
                               creating (gpg --gen-key) or listing keys (gpg --list-keys):
                               - given: pub rsa2048/A69BF163 2015-03-29
@@ -65,10 +67,12 @@ function encrypt_file {
   local decrypted_file=$1
   local encrypted_file=${decrypted_file}.gpg
 
-  test -n "$encrypted_file" || usage "ERROR: must specify file to encrypt"
+  test -f "$decrypted_file" || die "ERROR: file does not exist: $decrypted_file"
+  test -f "$KEYLIST" || die "ERROR: keylist not found at $KEYLIST"
 
   KEYIDS=`cat $KEYLIST | awk '{print $1}'`
   for id in $KEYIDS; do RECIPIENTS="$RECIPIENTS -r $id"; done
+  test -n "$RECIPIENTS" || die "ERROR: No keys found in $KEYLIST"
 
   echo gpg --no-skip-hidden-recipients $RECIPIENTS -o $encrypted_file -e $decrypted_file
   gpg --no-skip-hidden-recipients $RECIPIENTS -o $encrypted_file -e $decrypted_file
