Several improvements
Fix #2: decrypt to same dir
Import, trust, and sign on 'sync'
Cleanup output
fix 'clean'
Skip reimport if already imported
Deemphasize trust/sign commands for now

diff --git a/secretctl b/secretctl
--- a/secretctl
+++ b/secretctl
@@ -36,14 +36,10 @@ Commands:
   decrypt FILENAME ...    Decrypts one or more files with your keyring
                           Outputs the decrypted file(s) without the .gpg suffix
 
+  reencrypt FILENAME ...  Re-encrypts one or more files with your keyring
+                          This command simplifies the process of decrypting and then encrypting
+
   clean                   Remove all decrypted files that have an encrypted counterpart
-
-  sign                    Sign all imported keys with your own private key.
-                          This allows encryption of files without gpg prompting about untrusted keys
-
-  trust                   Set trust level on all imported public keys to '5' (full trust)
-                          This allows encryption of files without gpg prompting about untrusted
-                          keys if the keys are signed by another trusted user.
 
   list                    List all public keys which have been imported to your local store.
 
@@ -51,6 +47,15 @@ EOF
 
   exit 1
 }
+
+# Commands that probably aren't needed all that much anymore
+  # sign                    Sign all imported keys with your own private key.
+  #                         This allows encryption of files without gpg prompting about untrusted keys
+
+  # trust                   Set trust level on all imported public keys to '5' (full trust)
+  #                         This allows encryption of files without gpg prompting about untrusted
+  #                         keys if the keys are signed by another trusted user.
+  #                         Note: This currently would override the 'ultimate' trust given to your own key
 
 SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 WORKDIR=$PWD
@@ -96,7 +101,7 @@ function encrypt_file {
   test -n "$RECIPIENTS" || die "ERROR: No keys found in $KEYLIST"
 
   # echo gpg $RECIPIENTS -o $encrypted_file -e $decrypted_file
-  gpg $RECIPIENTS -o $encrypted_file -e $decrypted_file
+  gpg -q $RECIPIENTS -o $encrypted_file -e $decrypted_file
   echo "Encrypted as $encrypted_file"
 }
 
@@ -108,11 +113,11 @@ function encrypt_files {
 
 function decrypt_file {
   local encrypted_file=$1
-  local decrypted_file=`basename $encrypted_file .gpg`
+  local decrypted_file="$(dirname $encrypted_file)/$(basename $encrypted_file .gpg)"
 
   test -n "$encrypted_file" || usage "ERROR: must specify file to decrypt"
 
-  gpg -o $decrypted_file -d $encrypted_file
+  gpg -q -o $decrypted_file -d $encrypted_file
   echo "Decrypted to $decrypted_file"
 }
 
@@ -122,8 +127,23 @@ function decrypt_files {
   echo "Completed. Finished decrypting $# file(s)."
 }
 
+function reencrypt_files {
+  test -n "$1" || die "ERROR: Must specify at least one file to reencrypt"
+  for f in $@; do
+    echo "Decrypting $f"
+    rm -f "$(dirname $f)/$(basename $f .gpg)" > /dev/null
+    decrypt_file $f
+
+    echo "Encrypting $f"
+    rm "$f" > /dev/null
+    encrypt_file "$(dirname $f)/$(basename $f .gpg)"
+    rm "$(dirname $f)/$(basename $f .gpg)" > /dev/null
+  done
+  echo "Completed. Finished reencrypting $# file(s)."
+}
+
 function export_key {
-  local keyid="$1"
+  local keyid=$(echo $1 | sed 's/^.*\///')
   local keyname="${2:-${USER}_$(hostname)}"
   local keyfile="$KEYDIR/$keyname.pub"
 
@@ -136,10 +156,10 @@ function export_key {
   fi
 
   if [[ -f "$keyfile" ]]; then
-    die "Public key file with that name already exists. To replace it, remove it and it's keylist entry and rerun."
+    die "Public key file '$keyfile' already exists. To replace it, remove it and it's keylist entry and rerun."
   fi
 
-  gpg --export --armor -o $keyfile "$keyid"
+  gpg --export --armor -o $keyfile "$keyid" | grep -v "WARNING" || die "Not a valid KEYID"
   echo "$keyid $keyname" >> $KEYLIST
   echo "Complete. Sharing $keyid as $keyname and added to the keylist."
 }
@@ -153,11 +173,20 @@ function export_keys {
   echo "Finished exporting all public keys."
 }
 
+function import_key {
+  local keyid=$1
+  local keypath=$2
+  echo "Importing $keypath"
+  gpg -q --import $keypath
+  trust_key $keyid
+  echo "Signing key: $id"
+  gpg -q --sign-key $id
+}
 
 function import_keys {
-  for key in $KEYDIR/*.pub; do
-    echo "Importing $key"
-    gpg --import $key
+  load_keys
+  for id in ${!KEYIDS[@]}; do
+    gpg --list-keys $id &>/dev/null || import_key $id "$KEYDIR/${KEYIDS["$id"]}.pub"
   done
 
   echo "Finished importing all public keys. Ready to encrypt."
@@ -172,15 +201,21 @@ function sign_keys {
   echo "Finished signing all public keys."
 }
 
-function trust_keys {
+function trust_key {
   # Trust levels: 6=ultimate, 5=full, 4=marginal, 3=untrusted, 2=unknown
   # Full ownership requires a trust path to some UserID on the key already.
   # Utimate should imply key ownership, would prefer to use trust-model=always then ultimate trust
+  local id=$1
+  local trustlevel=${2:-5} # Default trust level = 5
+  echo "Setting trust to $trustlevel for key: $id"
+  echo "$(gpg --fingerprint $id | egrep -o '([0-9A-F]{4}\s*){5,20}' | tr -d ' '):$trustlevel:" | gpg -q --import-ownertrust
+}
+
+function trust_keys {
   load_keys
   local trustlevel=5
   for id in ${!KEYIDS[@]}; do
-    echo "Setting trust for key: $id"
-    echo "$(gpg --fingerprint $id | egrep -o '([0-9A-F]{4}\s*){5,20}' | tr -d ' '):$trustlevel:" | gpg --import-ownertrust
+    trust_key $id $trustlevel
   done
   echo "Finished setting trust on all public keys. Ready to encrypt."
 }
@@ -196,7 +231,7 @@ function list_keys {
 # rm all files that have a .gpg counterpart
 function remove_decrypted_files {
   local cleandir=${1:-$WORKDIR}
-  find $cleandir -type f -name "*.gpg" -exec basename '{}' '.gpg' \; | xargs rm -fv
+  find $cleandir -type f -name "*.gpg" -exec sh -c 'echo $(dirname {})/$(basename {} .gpg)' \; | xargs rm -fv
 }
 
 CMD=$1
@@ -209,17 +244,19 @@ case $CMD in
         export_key $@ ;;
     sync )
         import_keys ;;
-    sign )
-        sign_keys ;;
-    trust )
-        trust_keys ;;
     encrypt )
         encrypt_files $@ ;;
     decrypt )
         decrypt_files $@ ;;
+    reencrypt )
+        reencrypt_files $@ ;;
     clean )
         remove_decrypted_files $@ ;;
     # undocumented
+    sign )
+        sign_keys ;;
+    trust )
+        trust_keys ;;
     export )
         export_keys ;;
     * )
