Support batch encryption/decryption

diff --git a/secretctl b/secretctl
--- a/secretctl
+++ b/secretctl
@@ -30,11 +30,11 @@ Commands:
   import                  Imports all public keys in the keydir into your keychain
                           This allows encryption of files that can be decrypted by others
 
-  encrypt FILENAME        Encrypts a file with all the public keys in the keydir
-                          Outputs the encrypted file as FILENAME.gpg
+  encrypt FILENAME ...    Encrypts one or more files with all the public keys in the keydir
+                          Outputs the encrypted file(s) as FILENAME.gpg
 
-  decrypt FILENAME        Decrypts a file with your keyring
-                          Outputs the decrypted file without the .gpg suffix
+  decrypt FILENAME ...    Decrypts one or more files with your keyring
+                          Outputs the decrypted file(s) without the .gpg suffix
 
   clean                   Remove all decrypted files that have an encrypted counterpart
 
@@ -76,9 +76,14 @@ function encrypt_file {
   for id in $KEYIDS; do RECIPIENTS="$RECIPIENTS -r $id"; done
   test -n "$RECIPIENTS" || die "ERROR: No keys found in $KEYLIST"
 
-  echo gpg --no-skip-hidden-recipients $RECIPIENTS -o $encrypted_file -e $decrypted_file
   gpg --no-skip-hidden-recipients $RECIPIENTS -o $encrypted_file -e $decrypted_file
-  echo "Complete. Encrypted to $encrypted_file"
+  echo "Encrypted as $encrypted_file"
+}
+
+function encrypt_files {
+  test -n "$1" || die "ERROR: Must specify at least one file to encrypt"
+  for f in $@; do echo "Encrypting $f"; encrypt_file $f; done
+  echo "Completed. Finished encrypting $# file(s)."
 }
 
 function decrypt_file {
@@ -89,6 +94,12 @@ function decrypt_file {
 
   gpg -o $decrypted_file -d $encrypted_file
   echo "Complete. Decrypted to $decrypted_file"
+}
+
+function decrypt_files {
+  test -n "$1" || die "ERROR: Must specify at least one file to decrypt"
+  for f in $@; do echo "Encrypting $f"; decrypt_file $f; done
+  echo "Completed. Finished decrypting $# file(s)."
 }
 
 function export_keys {
@@ -129,15 +140,18 @@ function remove_decrypted_files {
   find $cleandir -type f -name "*.gpg" -exec basename '{}' '.gpg' \; | xargs rm -fv
 }
 
-case $1 in
+CMD=$1
+shift || usage
+
+case $CMD in
     export )
-        export_keys "$2" "$3" ;;
+        export_keys $@ ;;
     import )
         import_keys ;;
     encrypt )
-        encrypt_file "$2" ;;
+        encrypt_files $@ ;;
     decrypt )
-        decrypt_file "$2" ;;
+        decrypt_files $@ ;;
     clean )
         remove_decrypted_files "$2" ;;
     * )
