Adding 'list', 'sign' and 'trust' actions
Adding actions to:
- List all public keys in local keystore
- Sign all public keys in local keystore with your private key
- Set the trust level of all public keys in local keystore to 'ultimate'

diff --git a/secretctl b/secretctl
--- a/secretctl
+++ b/secretctl
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -e
 
@@ -38,6 +38,14 @@ Commands:
 
   clean                   Remove all decrypted files that have an encrypted counterpart
 
+  sign                    Sign all imported keys with your own private key
+
+  trust                   Set trust level on all imported public keys to '5' (ultimate trust)
+                          This allows encryption of files with out gpg prompting about untrusted
+                          keys.
+
+  list                    List all public keys which have been imported to your local store.
+
 EOF
 
   exit 1
@@ -57,6 +65,7 @@ upsearch $KEYDIRNAME || cd $WORKDIR
 KEYDIR=$PWD/$KEYDIRNAME
 KEYLIST=$KEYDIR/keylist
 cd $WORKDIR
+declare -A KEYIDS
 
 
 function die {
@@ -65,16 +74,25 @@ function die {
 }
 
 
+function load_keys {
+  test -f "$KEYLIST" || die "ERROR: keylist not found at $KEYLIST"
+  #KEYIDS=`cat $KEYLIST | awk '{print $1}'`
+    while IFS=$'\n' read -r line; do
+        keyid=$(echo $line | awk '{print $1}')
+        keyname=$(echo $line | awk '{print $2}')
+        KEYIDS+=(["$keyid"]="$keyname")
+    done < $KEYLIST
+}
+
 function encrypt_file {
+  load_keys
+
   local decrypted_file=$1
   local encrypted_file=${decrypted_file}.gpg
-
   test -f "$decrypted_file" || die "ERROR: file does not exist: $decrypted_file"
-  test -f "$KEYLIST" || die "ERROR: keylist not found at $KEYLIST"
 
-  KEYIDS=`cat $KEYLIST | awk '{print $1}'`
   RECIPIENTS=""
-  for id in $KEYIDS; do RECIPIENTS="$RECIPIENTS -r $id"; done
+  for id in ${!KEYIDS[@]}; do RECIPIENTS="$RECIPIENTS -r $id"; done
   test -n "$RECIPIENTS" || die "ERROR: No keys found in $KEYLIST"
 
   # echo gpg $RECIPIENTS -o $encrypted_file -e $decrypted_file
@@ -135,6 +153,34 @@ function import_keys {
   echo "Finished importing all public keys. Ready to encrypt."
 }
 
+function sign_keys {
+  load_keys
+  for id in ${!KEYIDS[@]}; do
+    echo "Signing key: $id"
+    gpg --sign-key $id
+    gpg --armor --export $id > $KEYDIR/${KEYIDS["$id"]}.pub
+  done
+  echo "Finished signing all public keys."
+}
+
+function trust_keys {
+  # Assuming ultimate trust, this could be modified to set specific trust levels
+  load_keys
+  for id in ${!KEYIDS[@]}; do
+    echo "Setting trust for key: $id"
+    echo "$(gpg --fingerprint $id | egrep -o '([0-9A-F]{4}\s*){5,20}' | tr -d ' '):5:" | gpg --import-ownertrust
+  done
+  echo "Finished setting trust on all public keys. Ready to encrypt."
+}
+
+function list_keys {
+  load_keys
+  printf "ID\tName\n"
+  for id in ${!KEYIDS[@]}; do
+      printf "%s\t%s\n" $id ${KEYIDS["$id"]}
+  done
+}
+
 
 # rm all files that have a .gpg counterpart
 function remove_decrypted_files {
@@ -146,10 +192,16 @@ CMD=$1
 shift || usage
 
 case $CMD in
+    list )
+        list_keys ;;
     export )
         export_keys $@ ;;
     import )
         import_keys ;;
+    sign )
+        sign_keys ;;
+    trust )
+        trust_keys ;;
     encrypt )
         encrypt_files $@ ;;
     decrypt )
